dbt_pagila:
  outputs:
    source:
      dbname: postgres
      host: localhost
      pass: '123456'
      port: 5432
      schema: source
      threads: 1
      type: postgres
      user: postgres
  target: source
